In [127]:
import numpy as np 
import pandas as pd 

In [128]:
car= pd.read_csv("car_data.csv")

In [129]:
car.head(40)

name   company  year          Price   
0     Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000  \
1                  Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000   
2               Maruti Suzuki Alto 800 Vxi    Maruti  2018  Ask For Price   
3   Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       3,25,000   
4         Ford EcoSport Titanium 1.5L TDCi      Ford  2014       5,75,000   
5         Ford EcoSport Titanium 1.5L TDCi      Ford  2015  Ask For Price   
6                                Ford Figo      Ford  2012       1,75,000   
7                              Hyundai Eon   Hyundai  2013       1,90,000   
8         Ford EcoSport Ambiente 1.5L TDCi      Ford  2016       8,30,000   
9           Maruti Suzuki Alto K10 VXi AMT    Maruti  2015       2,50,000   
10             Skoda Fabia Classic 1.2 MPI     Skoda  2010       1,82,000   
11              Maruti Suzuki Stingray VXi    Maruti  2015       3,15,000   
12             Hyundai Elite i20 Magna 1.2   Hyundai  2014       4,15,000   
13              Mahindra Scorpio SLE BS IV  Mahindra  2015       3,20,000   
14    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000   
15                 Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000   
16                                 Audi A8      Audi  2017      10,00,000   
17                                 Audi Q7      Audi  2014       5,00,000   
18                    Mahindra Scorpio S10  Mahindra  2016       3,50,000   
19                  Maruti Suzuki Alto 800    Maruti  2014       1,60,000   
20                    Mahindra Scorpio S10  Mahindra  2016       3,50,000   
21                    Mahindra Scorpio S10  Mahindra  2016       3,10,000   
22              Maruti Suzuki Alto 800 Vxi    Maruti  2015         75,000   
23                  Hyundai i20 Sportz 1.2   Hyundai  2012       1,00,000   
24                  Hyundai i20 Sportz 1.2   Hyundai  2012       1,00,000   
25                  Hyundai i20 Sportz 1.2   Hyundai  2012       1,00,000   
26               Maruti Suzuki Alto 800 Lx    Maruti  2017       1,90,000   
27         Maruti Suzuki Vitara Brezza ZDi    Maruti  2016       2,90,000   
28                   Maruti Suzuki Alto LX    Maruti  2008         95,000   
29                      Mahindra Bolero DI  Mahindra  2017       1,80,000   
30           Maruti Suzuki Swift Dzire ZDi    Maruti  2014       3,85,000   
31                Mahindra Scorpio S10 4WD  Mahindra  2015       2,50,000   
32           Maruti Suzuki Swift Vdi BSIII    Maruti  2017       1,80,000   
33        Maruti Suzuki Wagon R VXi BS III    Maruti  2013       1,05,000   
34         Maruti Suzuki Wagon R VXi Minor    Maruti  2013       1,05,000   
35         Toyota Innova 2.0 G 8 STR BS IV    Toyota  2012       6,50,000   
36                 Renault Lodgy 85 PS RXL   Renault  2018       6,89,999   
37      Skoda Yeti Ambition 2.0 TDI CR 4x2     Skoda  2012       4,48,000   
38          Maruti Suzuki Baleno Delta 1.2    Maruti  2017       5,49,000   
39   Renault Duster 110 PS RxZ Diesel Plus   Renault  2012       5,01,000   

    kms_driven fuel_type  
0   45,000 kms    Petrol  
1       40 kms    Diesel  
2   22,000 kms    Petrol  
3   28,000 kms    Petrol  
4   36,000 kms    Diesel  
5   59,000 kms    Diesel  
6   41,000 kms    Diesel  
7   25,000 kms    Petrol  
8   24,530 kms    Diesel  
9   60,000 kms    Petrol  
10  60,000 kms    Petrol  
11  30,000 kms    Petrol  
12  32,000 kms    Petrol  
13  48,660 kms    Diesel  
14  45,000 kms    Petrol  
15      40 kms    Diesel  
16   4,000 kms    Petrol  
17  16,934 kms    Diesel  
18  43,000 kms    Diesel  
19  35,550 kms    Petrol  
20  43,000 kms    Diesel  
21  39,522 kms    Diesel  
22  39,000 kms    Petrol  
23  55,000 kms    Petrol  
24  55,000 kms    Petrol  
25  55,000 kms    Petrol  
26  72,000 kms    Petrol  
27  15,975 kms    Diesel  
28  70,000 kms    Petrol  
29  23,452 kms    Diesel  
30  35,522 kms    Diesel  
31  48,508 kms  

In [130]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB


In [131]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [132]:
car['name'].unique()

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Maruti Suzuki Alto 800 Vxi',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Hyundai i20 Sportz 1.2', 'Maruti Suzuki Alto 800 Lx',
       'Maruti Suzuki Vitara Brezza ZDi', 'Maruti Suzuki Alto LX',
       'Mahindra Bolero DI', 'Maruti Suzuki Swift Dzire ZDi',
       'Mahindra Scorpio S10 4WD', 'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maru

In [133]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,5

Quality
Year is not in integer form
Year have many extra values
Price have one Ask for value entry 
Price is not in integer and have comma
Kms have kms written to it and it is not in integer
Take only first three letters of name
fuel type has nan columns

# Cleaning

In [134]:
backup = car.copy()

In [135]:
#if year is string and numeric then keep it otherwise discard it
car = car[car['year'].str.isnumeric()]

In [136]:
#convert year from object to integer

car['year'].astype(int)

0      2007
1      2006
2      2018
3      2014
4      2014
       ... 
886    2009
888    2018
889    2013
890    2014
891    2014
Name: year, Length: 842, dtype: int32

In [137]:
car['year'] = car['year'].astype(int)

In [138]:
car['year'].unique()

array([2007, 2006, 2018, 2014, 2015, 2012, 2013, 2016, 2010, 2017, 2008,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [139]:
car=car[car['Price']!='Ask For Price']

In [140]:
car['Price'] = car['Price'].str.replace(',','').astype(int)

In [141]:
car['kms_driven'] = car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [142]:
# As few km have entry as petrol 
car = car[car['kms_driven'].str.isnumeric()]

In [143]:
car = car[~car['fuel_type'].isna()]

In [144]:
car['name'] = backup['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [145]:
car['name'] = car['name'].str.lower()

In [146]:
car

name   company  year   Price kms_driven fuel_type
0       hyundai santro xing   Hyundai  2007   80000      45000    Petrol
1       mahindra jeep cl550  Mahindra  2006  425000         40    Diesel
3         hyundai grand i10   Hyundai  2014  325000      28000    Petrol
4    ford ecosport titanium      Ford  2014  575000      36000    Diesel
6                 ford figo      Ford  2012  175000      41000    Diesel
..                      ...       ...   ...     ...        ...       ...
883      maruti suzuki ritz    Maruti  2011  270000      50000    Petrol
885          tata indica v2      Tata  2009  110000      30000    Diesel
886    toyota corolla altis    Toyota  2009  300000     132000    Petrol
888            tata zest xm      Tata  2018  260000      27000    Diesel
889      mahindra quanto c8  Mahindra  2013  390000      40000    Diesel

[816 rows x 6 columns]

In [147]:
#to reset the index

car.reset_index()

index                    name   company  year   Price kms_driven   
0        0     hyundai santro xing   Hyundai  2007   80000      45000  \
1        1     mahindra jeep cl550  Mahindra  2006  425000         40   
2        3       hyundai grand i10   Hyundai  2014  325000      28000   
3        4  ford ecosport titanium      Ford  2014  575000      36000   
4        6               ford figo      Ford  2012  175000      41000   
..     ...                     ...       ...   ...     ...        ...   
811    883      maruti suzuki ritz    Maruti  2011  270000      50000   
812    885          tata indica v2      Tata  2009  110000      30000   
813    886    toyota corolla altis    Toyota  2009  300000     132000   
814    888            tata zest xm      Tata  2018  260000      27000   
815    889      mahindra quanto c8  Mahindra  2013  390000      40000   

    fuel_type  
0      Petrol  
1      Diesel  
2      Petrol  
3      Diesel  
4      Diesel  
..        ...  
811    Petrol  
812    Diesel  
813    Petrol  
814    Diesel  
815    Diesel  

[816 rows x 7 columns]

In [148]:
#to remove extra column of old index
car = car.reset_index(drop =True)

In [149]:
car['company'] = car['company'].str.lower()

In [150]:
car.describe()

year         Price
count   816.000000  8.160000e+02
mean   2012.444853  4.117176e+05
std       4.002992  4.751844e+05
min    1995.000000  3.000000e+04
25%    2010.000000  1.750000e+05
50%    2013.000000  2.999990e+05
75%    2015.000000  4.912500e+05
max    2019.000000  8.500003e+06

In [151]:
#to find outlier in price
car[car['Price']>6e6]

name   company  year    Price kms_driven fuel_type
534  mahindra xuv500 w6  mahindra  2014  8500003      45000    Diesel

In [152]:
car = car[car['Price']<6e6].reset_index(drop = True)

In [153]:
car

name   company  year   Price kms_driven fuel_type
0       hyundai santro xing   hyundai  2007   80000      45000    Petrol
1       mahindra jeep cl550  mahindra  2006  425000         40    Diesel
2         hyundai grand i10   hyundai  2014  325000      28000    Petrol
3    ford ecosport titanium      ford  2014  575000      36000    Diesel
4                 ford figo      ford  2012  175000      41000    Diesel
..                      ...       ...   ...     ...        ...       ...
810      maruti suzuki ritz    maruti  2011  270000      50000    Petrol
811          tata indica v2      tata  2009  110000      30000    Diesel
812    toyota corolla altis    toyota  2009  300000     132000    Petrol
813            tata zest xm      tata  2018  260000      27000    Diesel
814      mahindra quanto c8  mahindra  2013  390000      40000    Diesel

[815 rows x 6 columns]

In [154]:
car['company'].unique()

array(['hyundai', 'mahindra', 'ford', 'maruti', 'skoda', 'audi', 'toyota',
       'renault', 'honda', 'datsun', 'mitsubishi', 'tata', 'volkswagen',
       'chevrolet', 'mini', 'bmw', 'nissan', 'hindustan', 'fiat', 'force',
       'mercedes', 'land', 'jaguar', 'jeep', 'volvo'], dtype=object)

## Data is cleaned

In [155]:
car.to_csv('cleaned_car.csv')

# Model

In [156]:
X = car.drop(['Price'], axis=1)
y = car['Price']

In [157]:
X

name   company  year kms_driven fuel_type
0       hyundai santro xing   hyundai  2007      45000    Petrol
1       mahindra jeep cl550  mahindra  2006         40    Diesel
2         hyundai grand i10   hyundai  2014      28000    Petrol
3    ford ecosport titanium      ford  2014      36000    Diesel
4                 ford figo      ford  2012      41000    Diesel
..                      ...       ...   ...        ...       ...
810      maruti suzuki ritz    maruti  2011      50000    Petrol
811          tata indica v2      tata  2009      30000    Diesel
812    toyota corolla altis    toyota  2009     132000    Petrol
813            tata zest xm      tata  2018      27000    Diesel
814      mahindra quanto c8  mahindra  2013      40000    Diesel

[815 rows x 5 columns]

In [158]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...  
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [159]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state= 433)

In [160]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [161]:
ohe = OneHotEncoder()

In [162]:
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [163]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_),['name','company','fuel_type']),remainder = 'passthrough')

In [164]:
lr = LinearRegression()

In [165]:
pipe = make_pipeline(column_trans,lr)

In [166]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['audi a3 cabriolet', 'audi a4 1.8', 'audi a4 2.0', 'audi a6 2.0',
       'audi a8', 'audi q3 2.0', 'audi q5 2.0', 'audi q7', 'bmw 3 series',
       'bmw 5 series', 'bmw 7 series', 'bmw x1', 'bmw x1 sdrive20d',
       'bmw x1 xdrive20d', 'chevrolet beat', 'chevrolet beat...
                                                                            array(['audi', 'bmw', 'chevrolet', 'datsun', 'fiat', 'force', 'ford',
       'hindustan', 'honda', 'hyundai', 'jaguar', 'jeep', 'land',
       'mahindra', 'maruti', 'mercedes', 'mini', 'mitsubishi', 'nissan',
       'renault', 'skoda', 'tata', 'toyota', 'volkswagen', 'volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [167]:
y_pred = pipe.predict(X_test)

In [168]:
r2_score(y_test,y_pred)

0.8462074778105438

In [169]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [170]:
np.argmax(scores)

433

In [171]:
scores[433]

0.8462074778105438

In [172]:
import pickle

In [173]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [174]:
pipe.predict((pd.DataFrame([['maruti suzuki swift','maruti',2018,50000,'Petrol']], columns = ['name','company','year','kms_driven','fuel_type'])))

array([388914.9265459])

In [175]:
pipe.predict(pd.DataFrame([['hyundai i20','hyundai',2012,65000,'Petrol']], columns = ['name','company','year','kms_driven','fuel_type']))

array([281628.08004589])

In [176]:
car_name=input("Enter name of the car: ")
car_company=input("Enter name of the car company: ")
car_year=int(input("year: "))
car_kms=int(input("kms driven: "))
car_fueltype=input("Enter type of fuel: ")

car_name=car_name.lower()
car_company=car_company.lower()

pipe.predict(pd.DataFrame([[car_name,car_company,car_year,car_kms,car_fueltype]], columns = ['name','company','year','kms_driven','fuel_type']))


array([287182.4170021])